# Generated by Django 2.2.5 on 2019-09-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torre', models.CharField(max_length=10)),
                ('piso', models.CharField(max_length=10)),
                ('apartamento', models.CharField(max_length=5)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parqueo.Propietario')),
            ],
        ),
    ]
